# Generated by Django 2.1.7 on 2019-05-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('AUDITORIUM', 'AUDITORIUM'), ('PROFESSOR', 'PROFESSOR'), ('GROUP', 'GROUP')], max_length=20)),
                ('object_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Lesson name'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'professor', 'auditorium', 'group', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='conflict',
            name='first_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_lesson', to='scheduler.Lesson'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='second_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_lesson', to='scheduler.Lesson'),
        ),
    ]
