# Generated by Django 2.1.7 on 2019-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Lesson name'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'professor', 'auditorium', 'group', 'start_time', 'end_time')},
        ),
    ]
