# Generated by Django 2.1.7 on 2019-04-23 17:34

from django.db import migrations, models
import scheduler.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190402_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='color',
            field=models.CharField(default=scheduler.models.random_color, max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default=scheduler.models.random_color, max_length=10),
        ),
    ]
