# Generated by Django 2.1.7 on 2019-05-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20190423_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('AUDITORIUM', 'AUDITORIUM'), ('PROFESSOR', 'PROFESSOR'), ('GROUP', 'GROUP')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('first_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_lesson', to='scheduler.Lesson')),
                ('second_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_lesson', to='scheduler.Lesson')),
            ],
        ),
    ]
