# Generated by Django 2.1.7 on 2019-05-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='first_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_lesson', to='scheduler.Lesson'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='second_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_lesson', to='scheduler.Lesson'),
        ),
    ]
